#!/bin/sh
set -eu

RAW_BASE="${WAN2VAULT_RAW_BASE:-https://raw.githubusercontent.com/weigefenxiang/WeiG-WAN2-Vault/main}"
CONFIG_FILE="/etc/wan2-vault.conf"
REPORTER="/usr/bin/wan2-vault-report"
CLI="/usr/bin/wan2-vault"
VERSION_FILE="/usr/share/wan2-vault/VERSION"
STATE_DIR="/etc/wan2-vault-state"
CRON_FILE="/etc/crontabs/root"
CRON_MARK="# WeiG-WAN2-Vault"
SYSUPGRADE="/etc/sysupgrade.conf"

fail() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

[ "$(id -u)" = "0" ] || fail "Run this installer as root."
for cmd in ubus jsonfilter curl sed grep sort; do
    command -v "$cmd" >/dev/null 2>&1 || fail "Missing required command: $cmd"
done

printf '\nWeiG WAN Vault - OpenWrt installer\n\n'

while :; do
    printf 'Public hostname (example: notify.example.com): '
    IFS= read -r HOSTNAME
    HOSTNAME="${HOSTNAME#http://}"
    HOSTNAME="${HOSTNAME#https://}"
    HOSTNAME="${HOSTNAME%%/*}"
    case "$HOSTNAME" in
        ''|*[!A-Za-z0-9.-]*|.*|*..*|*.) echo "Invalid hostname." ;;
        *.*) break ;;
        *) echo "Invalid hostname." ;;
    esac
done

printf '\nDetected WAN candidates:\n'
FOUND=0
for obj in $(ubus list 'network.interface.*' 2>/dev/null); do
    name="${obj#network.interface.}"
    [ "$name" = "$obj" ] && continue
    [ "$name" = "loopback" ] && continue
    status="$(ubus call "$obj" status 2>/dev/null || true)"
    up="$(printf '%s' "$status" | jsonfilter -e '@.up' 2>/dev/null || true)"
    ip="$(printf '%s' "$status" | jsonfilter -e '@["ipv4-address"][0].address' 2>/dev/null || true)"
    dev="$(printf '%s' "$status" | jsonfilter -e '@.l3_device' 2>/dev/null || true)"
    targets="$(printf '%s' "$status" | jsonfilter -e '@.route[*].target' 2>/dev/null || true)"
    if [ "$up" = "true" ] && [ -n "$ip" ] && [ -n "$dev" ] && printf '%s\n' "$targets" | grep -qx '0.0.0.0'; then
        printf '  %-16s %-18s %s\n' "$name" "$ip" "$dev"
        FOUND=1
    fi
done
[ "$FOUND" -eq 1 ] || echo "  (none currently up; auto mode can discover them later)"

printf '\nTracking mode:\n'
printf '  1) Auto - track every active IPv4 default-route WAN (recommended)\n'
printf '  2) Manual - track only named OpenWrt interfaces\n'
printf 'Select [1]: '
IFS= read -r MODE_CHOICE
MODE_CHOICE="${MODE_CHOICE:-1}"

case "$MODE_CHOICE" in
    1)
        MODE="auto"
        INTERFACES=""
        ;;
    2)
        MODE="manual"
        while :; do
            printf 'Interfaces separated by spaces (example: WAN WAN2): '
            IFS= read -r INTERFACES
            [ -n "$INTERFACES" ] || { echo "At least one interface is required."; continue; }
            valid=1
            for name in $INTERFACES; do
                case "$name" in ''|*[!A-Za-z0-9_.:@-]*) valid=0 ;; esac
            done
            [ "$valid" -eq 1 ] && break
            echo "Invalid interface name."
        done
        ;;
    *) fail "Invalid selection." ;;
esac

printf 'WRITE_TOKEN: '
stty -echo
IFS= read -r WRITE_TOKEN
stty echo
printf '\n'
[ "${#WRITE_TOKEN}" -eq 64 ] || fail "WRITE_TOKEN must be the 64-character token generated by the VPS installer."
case "$WRITE_TOKEN" in
    *[!0-9A-Fa-f]*) fail "WRITE_TOKEN contains invalid characters." ;;
esac

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"; unset WRITE_TOKEN || true' EXIT INT TERM

fetch_file() {
    rel="$1"
    out="$2"
    curl -fsSL "$RAW_BASE/openwrt/$rel" -o "$out"
}

fetch_file "wan2-ipnotify.sh" "$TMP_DIR/wan2-ipnotify.sh"
fetch_file "wan2-vault" "$TMP_DIR/wan2-vault"
curl -fsSL "$RAW_BASE/VERSION" -o "$TMP_DIR/VERSION"

sh -n "$TMP_DIR/wan2-ipnotify.sh"
sh -n "$TMP_DIR/wan2-vault"

umask 077
cat > "$CONFIG_FILE" <<EOF
HOSTNAME='$HOSTNAME'
MODE='$MODE'
INTERFACES='$INTERFACES'
WRITE_TOKEN='$WRITE_TOKEN'
EOF
chmod 600 "$CONFIG_FILE"
unset WRITE_TOKEN

install -m 700 "$TMP_DIR/wan2-ipnotify.sh" "$REPORTER"
install -m 700 "$TMP_DIR/wan2-vault" "$CLI"
mkdir -p "$(dirname "$VERSION_FILE")" "$STATE_DIR/interfaces"
install -m 644 "$TMP_DIR/VERSION" "$VERSION_FILE"
chmod 700 "$STATE_DIR" "$STATE_DIR/interfaces"

mkdir -p /etc/crontabs
touch "$CRON_FILE"
TMP_CRON="$TMP_DIR/root.cron"
grep -vF "$CRON_MARK" "$CRON_FILE" > "$TMP_CRON" 2>/dev/null || true
grep -vF "/etc/wan2-ipnotify.sh" "$TMP_CRON" > "$TMP_DIR/root.cron.clean" 2>/dev/null || true
{
    cat "$TMP_DIR/root.cron.clean"
    echo "*/5 * * * * $REPORTER >/dev/null 2>&1 $CRON_MARK"
} > "$CRON_FILE"
chmod 600 "$CRON_FILE"
/etc/init.d/cron restart >/dev/null 2>&1 || true

rm -f /etc/hotplug.d/iface/95-wan2-ipnotify

touch "$SYSUPGRADE"
for f in "$CONFIG_FILE" "$STATE_DIR" "$REPORTER" "$CLI" "$VERSION_FILE" "$CRON_FILE"; do
    grep -qxF "$f" "$SYSUPGRADE" 2>/dev/null || echo "$f" >> "$SYSUPGRADE"
done

info "Running first report."
if FORCE=1 FORCE_INVENTORY=1 "$REPORTER"; then
    echo
    echo "Installation complete."
    echo "Mode:          $MODE"
    [ "$MODE" = "manual" ] && echo "Interfaces:    $INTERFACES"
    echo "Hostname:      $HOSTNAME"
    echo "Check cadence: every 5 minutes"
    echo
    echo "Useful commands:"
    echo "  wan2-vault status"
    echo "  wan2-vault interfaces"
    echo "  wan2-vault report"
    echo "  wan2-vault upgrade"
else
    echo
    echo "Installed, but the first report had errors."
    echo "Check: logread | grep wan2-vault"
    exit 2
fi
