#!/bin/sh
set -eu

RAW_BASE="${WAN2VAULT_RAW_BASE:-https://raw.githubusercontent.com/weigefenxiang/WeiG-WAN2-Vault/main}"
CONFIG_FILE="/etc/wan2-vault.conf"
REPORTER="/etc/wan2-ipnotify.sh"
HOTPLUG="/etc/hotplug.d/iface/95-wan2-ipnotify"
CRON_FILE="/etc/crontabs/root"
CRON_MARK="# WeiG-WAN2-Vault"
SYSUPGRADE="/etc/sysupgrade.conf"

fail() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

[ "$(id -u)" = "0" ] || fail "Run this installer as root."
for cmd in ubus jsonfilter curl date sed; do
    command -v "$cmd" >/dev/null 2>&1 || fail "Missing required command: $cmd"
done

printf '\nWeiG WAN2 Vault - OpenWrt installer\n\n'

while :; do
    printf 'Public hostname (example: notify.example.com): '
    IFS= read -r HOSTNAME
    HOSTNAME="${HOSTNAME#http://}"
    HOSTNAME="${HOSTNAME#https://}"
    HOSTNAME="${HOSTNAME%%/*}"
    case "$HOSTNAME" in
        ''|*[!A-Za-z0-9.-]*|.*|*..*|*.) echo "Invalid hostname." ;;
        *.*) break ;;
        *) echo "Invalid hostname." ;;
    esac
done

while :; do
    printf 'WAN interface [WAN2]: '
    IFS= read -r WAN_INTERFACE
    WAN_INTERFACE="${WAN_INTERFACE:-WAN2}"
    case "$WAN_INTERFACE" in
        ''|*[!A-Za-z0-9_.:@-]*) echo "Invalid interface name." ;;
        *) break ;;
    esac
done

if ! ubus call "network.interface.${WAN_INTERFACE}" status >/dev/null 2>&1; then
    fail "OpenWrt interface '${WAN_INTERFACE}' does not exist."
fi

printf 'WRITE_TOKEN: '
stty -echo
IFS= read -r WRITE_TOKEN
stty echo
printf '\n'
[ "${#WRITE_TOKEN}" -eq 64 ] || fail "WRITE_TOKEN must be the 64-character token generated by the VPS installer."
case "$WRITE_TOKEN" in
    *[!0-9A-Fa-f]*) fail "WRITE_TOKEN contains invalid characters." ;;
esac

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"; unset WRITE_TOKEN || true' EXIT INT TERM

fetch_file() {
    rel="$1"
    out="$2"
    if command -v wget >/dev/null 2>&1; then
        wget -qO "$out" "$RAW_BASE/openwrt/$rel"
    else
        curl -fsSL "$RAW_BASE/openwrt/$rel" -o "$out"
    fi
}

SCRIPT_DIR="$(CDPATH= cd "$(dirname "$0")" 2>/dev/null && pwd -P || true)"
if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/wan2-ipnotify.sh" ]; then
    cp "$SCRIPT_DIR/wan2-ipnotify.sh" "$TMP_DIR/wan2-ipnotify.sh"
else
    fetch_file "wan2-ipnotify.sh" "$TMP_DIR/wan2-ipnotify.sh"
fi
if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/95-wan2-ipnotify" ]; then
    cp "$SCRIPT_DIR/95-wan2-ipnotify" "$TMP_DIR/95-wan2-ipnotify"
else
    fetch_file "95-wan2-ipnotify" "$TMP_DIR/95-wan2-ipnotify"
fi

sh -n "$TMP_DIR/wan2-ipnotify.sh"
sh -n "$TMP_DIR/95-wan2-ipnotify"

umask 077
cat > "$CONFIG_FILE" <<EOF
HOSTNAME='$HOSTNAME'
WAN_INTERFACE='$WAN_INTERFACE'
WRITE_TOKEN='$WRITE_TOKEN'
REFRESH_INTERVAL='1800'
EOF
chmod 600 "$CONFIG_FILE"
unset WRITE_TOKEN

cp "$TMP_DIR/wan2-ipnotify.sh" "$REPORTER"
chmod 700 "$REPORTER"
mkdir -p /etc/hotplug.d/iface
cp "$TMP_DIR/95-wan2-ipnotify" "$HOTPLUG"
chmod 700 "$HOTPLUG"

mkdir -p /etc/crontabs
touch "$CRON_FILE"
TMP_CRON="$TMP_DIR/root.cron"
grep -vF "$CRON_MARK" "$CRON_FILE" > "$TMP_CRON" 2>/dev/null || true
{
    cat "$TMP_CRON"
    echo "*/10 * * * * $REPORTER >/dev/null 2>&1 $CRON_MARK"
} > "$CRON_FILE"
chmod 600 "$CRON_FILE"
/etc/init.d/cron restart >/dev/null 2>&1 || true

touch "$SYSUPGRADE"
for f in "$CONFIG_FILE" "$REPORTER" "$HOTPLUG" "$CRON_FILE"; do
    grep -qxF "$f" "$SYSUPGRADE" 2>/dev/null || echo "$f" >> "$SYSUPGRADE"
done

info "Running first forced report through ${WAN_INTERFACE}."
if FORCE=1 "$REPORTER"; then
    echo
    echo "Installation complete."
    echo "WAN interface: $WAN_INTERFACE"
    echo "Hostname:      $HOSTNAME"
    echo "Inbound HTTP/HTTPS ports opened by this project: 0"
else
    echo
    echo "Installed, but the first report failed."
    echo "Check: logread | grep wan2-vault"
    exit 2
fi
